### ISSUE TITLE
Failed to activate the Obfuscate package

### ISSUE THREAD

**Issue by aamerio** [adamsanderson/obfuscate#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.0
**System**: Mac OS X 10.11.3
**Thrown From**: [Obfuscate](https://github.com/adamsanderson/obfuscate) package, v0.2.0
### Stack Trace

Failed to activate the Obfuscate package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/cookedapple/.atom/packages/obfuscate/lib/obfuscate.coffee:5:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -7:44.1.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -5:27.9.0 settings-view:install-packages-and-themes (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Obfuscate, v0.2.0
color-picker, v2.1.1
minimap, v4.19.0
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by emecas** [comment]
having same issue

**Comment by adamsanderson** [comment]
Oh, I somehow missed this bug when it was first opened, many sorries!
I suspect the API for Atom changed a bit over time, and this plugin hasn't been updated since I first wrote it.

**Comment by ghost** [comment]
Atom 28. This same problem...

**Comment by adamsanderson** [comment]
Hi folks, this is essentially unmaintained.  I really appreciate that people are trying it out, but I don't regularly use Atom anymore, and don't have the time to devote to this plugin.

I'd be more than willing to accept a pull request, or redirect people to a branch that would be maintained.
